-- --------------------------------------------------------
-- Servidor:                     127.0.0.1
-- Versão do servidor:           8.0.30 - MySQL Community Server - GPL
-- OS do Servidor:               Win64
-- HeidiSQL Versão:              12.1.0.6537
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Copiando estrutura do banco de dados para sampapoint
CREATE DATABASE IF NOT EXISTS `sampapoint` /*!40100 DEFAULT CHARACTER SET utf8mb3 COLLATE utf8mb3_bin */ /*!80016 DEFAULT ENCRYPTION='N' */;
USE `sampapoint`;

-- Copiando estrutura para tabela sampapoint.avaliacao
CREATE TABLE IF NOT EXISTS `avaliacao` (
  `codAvaliacao` int NOT NULL AUTO_INCREMENT,
  `codUsuario` int NOT NULL,
  `codLocal` int NOT NULL,
  `comentario` varchar(200) COLLATE utf8mb3_bin DEFAULT NULL,
  `notaEstrela` decimal(2,1) DEFAULT NULL,
  `dataPostagem` datetime NOT NULL,
  `nomeFotoAvaliacao` varchar(70) COLLATE utf8mb3_bin DEFAULT NULL,
  PRIMARY KEY (`codAvaliacao`),
  KEY `fk_perfil_avaliacao` (`codUsuario`),
  KEY `fk_lugar_avaliacao` (`codLocal`),
  CONSTRAINT `fk_lugar_avaliacao` FOREIGN KEY (`codLocal`) REFERENCES `lugar` (`codLocal`),
  CONSTRAINT `fk_perfil_avaliacao` FOREIGN KEY (`codUsuario`) REFERENCES `perfil` (`codUsuario`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_bin;

-- Copiando dados para a tabela sampapoint.avaliacao: ~0 rows (aproximadamente)

-- Copiando estrutura para tabela sampapoint.fotos_lugar
CREATE TABLE IF NOT EXISTS `fotos_lugar` (
  `codFotoslocal` int NOT NULL AUTO_INCREMENT,
  `codLocal` int NOT NULL,
  `nomeFotoLugar` varchar(70) COLLATE utf8mb3_bin NOT NULL,
  PRIMARY KEY (`codFotoslocal`),
  KEY `fk_lugar_fotoslugar` (`codLocal`),
  CONSTRAINT `fk_lugar_fotoslugar` FOREIGN KEY (`codLocal`) REFERENCES `lugar` (`codLocal`)
) ENGINE=InnoDB AUTO_INCREMENT=301 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_bin;

-- Copiando dados para a tabela sampapoint.fotos_lugar: ~257 rows (aproximadamente)
INSERT INTO `fotos_lugar` (`codFotoslocal`, `codLocal`, `nomeFotoLugar`) VALUES
	(36, 16, 'mmb1.jpg'),
	(37, 16, 'mmb2.jpg'),
	(38, 16, 'mmb3.jpg'),
	(39, 16, 'mmb4.jpg'),
	(40, 16, 'mmb5.jpg'),
	(41, 17, 'vetp1.jpg'),
	(42, 17, 'vetp2.jpg'),
	(43, 17, 'vetp3.jpg'),
	(44, 17, 'vetp4.jpg'),
	(45, 17, 'vetp5.jpg'),
	(46, 19, 'pecnpg1.jpg'),
	(47, 19, 'pecnpg2.jpg'),
	(48, 19, 'pecnpg3.jpg'),
	(49, 19, 'pecnpg4.jpg'),
	(50, 19, 'pecnpg5.jpg'),
	(51, 20, 'aps1.jpg'),
	(52, 20, 'aps2.jpg'),
	(53, 20, 'aps3.jpg'),
	(54, 20, 'aps4.jpg'),
	(55, 20, 'aps5.jpg'),
	(56, 23, 'pp1.jpg'),
	(57, 23, 'pp2.jpg'),
	(58, 23, 'pp3.jpg'),
	(59, 23, 'pp4.jpg'),
	(60, 23, 'pp5.jpg'),
	(61, 24, 'tm1.jpg'),
	(62, 24, 'tm2.jpg'),
	(63, 24, 'tm3.jpg'),
	(64, 24, 'tm4.jpg'),
	(65, 24, 'tm5.jpg'),
	(66, 25, 'pdp1.jpg'),
	(67, 25, 'pdp2.jpg'),
	(68, 25, 'pdp3.jpg'),
	(69, 25, 'pdp4.jpg'),
	(70, 25, 'pdp5.jpg'),
	(71, 26, 'bd1.jpg'),
	(72, 26, 'bd2.jpg'),
	(73, 26, 'bd3.jpg'),
	(74, 26, 'bd4.jpg'),
	(75, 26, 'bd5.jpg'),
	(76, 27, 'paea1.jpg'),
	(77, 27, 'paea2.jpg'),
	(78, 27, 'paea3.jpg'),
	(79, 27, 'paea4.jpg'),
	(80, 27, 'paea5.jpg'),
	(81, 28, 'emhe1.jpg'),
	(82, 28, 'emhe2.jpg'),
	(83, 28, 'emhe3.jpg'),
	(84, 28, 'emhe4.jpg'),
	(85, 29, 'efeg1.jpg'),
	(86, 29, 'efeg2.jpg'),
	(87, 29, 'efeg3.jpg'),
	(88, 29, 'efeg4.jpg'),
	(89, 29, 'efeg5.jpg'),
	(90, 30, 'phs1.jpg'),
	(91, 30, 'phs2.jpg'),
	(92, 30, 'phs3.jpg'),
	(93, 30, 'phs4.jpg'),
	(94, 30, 'phs5.jpg'),
	(95, 31, 'sac1.jpg'),
	(96, 31, 'sac2.jpg'),
	(97, 31, 'sac3.jpg'),
	(98, 31, 'sac4.jpg'),
	(99, 31, 'sac5.jpg'),
	(100, 32, 'pmsr1.jpg'),
	(101, 32, 'pmsr2.jpg'),
	(102, 32, 'pmsr3.jpg'),
	(103, 32, 'pmsr4.jpg'),
	(104, 32, 'pmsr5.jpg'),
	(105, 33, 'pmjsb1.jpg'),
	(106, 33, 'pmjsb2.jpg'),
	(107, 33, 'pmjsb3.jpg'),
	(108, 33, 'pmjsb4.jpg'),
	(109, 33, 'pmjsb5.jpg'),
	(110, 34, 'pc1.jpg'),
	(111, 34, 'pc2.jpg'),
	(112, 34, 'pc3.jpg'),
	(113, 34, 'pc4.jpg'),
	(114, 34, 'pc5.jpg'),
	(115, 35, 'pej1.jpg'),
	(116, 35, 'pej2.jpg'),
	(117, 35, 'pej3.jpg'),
	(118, 35, 'pej4.jpg'),
	(119, 35, 'pej5.jpg'),
	(120, 36, 'cqc1.jpg'),
	(121, 36, 'cqc2.jpg'),
	(122, 36, 'cqc3.jpg'),
	(123, 36, 'cqc4.jpg'),
	(124, 36, 'cqc5.jpg'),
	(125, 37, 'gat1.jpg'),
	(126, 37, 'gat2.jpg'),
	(127, 37, 'gat3.jpg'),
	(128, 37, 'gat4.jpg'),
	(129, 37, 'gat5.jpg'),
	(130, 38, 'tg1.jpg'),
	(131, 38, 'tg2.jpg'),
	(132, 38, 'tg3.jpg'),
	(133, 38, 'tg4.jpg'),
	(134, 38, 'tg5.jpg'),
	(135, 39, 'is1.jpg'),
	(136, 39, 'is2.jpg'),
	(137, 39, 'is3.jpg'),
	(138, 39, 'is4.jpg'),
	(139, 39, 'is5.jpg'),
	(140, 40, 'pbm1.jpg'),
	(141, 40, 'pbm2.jpg'),
	(142, 40, 'pbm3.jpg'),
	(143, 40, 'pbm4.jpg'),
	(144, 40, 'pbm5.jpg'),
	(145, 41, 'lp1.jpg'),
	(146, 41, 'lp2.jpg'),
	(147, 41, 'lp3.jpg'),
	(148, 41, 'lp4.jpg'),
	(149, 41, 'lp5.jpg'),
	(150, 42, 'tkj1.jpg'),
	(151, 42, 'tkj2.jpg'),
	(152, 42, 'tkj3.jpg'),
	(153, 42, 'tkj4.jpg'),
	(154, 42, 'tkj5.jpg'),
	(155, 43, 'cp1.jpg'),
	(156, 43, 'cp2.jpg'),
	(157, 43, 'cp3.jpg'),
	(158, 43, 'cp4.jpg'),
	(159, 44, 'pbv1.jpg'),
	(160, 44, 'pbv2.jpg'),
	(161, 44, 'pbv3.jpg'),
	(162, 44, 'pbv4.jpg'),
	(163, 44, 'pbv5.jpg'),
	(164, 45, 'mgigs1.jpg'),
	(165, 45, 'mgigs2.jpg'),
	(166, 45, 'mgigs3.jpg'),
	(167, 45, 'mgigs4.jpg'),
	(168, 45, 'mgigs5.jpg'),
	(169, 46, 'pemc1.jpg'),
	(170, 46, 'pemc2.jpg'),
	(171, 46, 'pemc3.jpg'),
	(172, 46, 'pemc4.jpg'),
	(173, 46, 'pemc5.jpg'),
	(174, 47, 'pej1.jpg'),
	(175, 47, 'pej2.jpg'),
	(176, 47, 'pej3.jpg'),
	(177, 47, 'pej4.jpg'),
	(178, 47, 'pej5.jpg'),
	(179, 48, 'jps1.jpg'),
	(180, 48, 'jps2.jpg'),
	(181, 48, 'jps3.jpg'),
	(182, 48, 'jps4.jpg'),
	(183, 49, 've1.jpg'),
	(184, 49, 've2.jpg'),
	(185, 49, 've3.jpg'),
	(186, 49, 've4.jpg'),
	(187, 49, 've5.jpg'),
	(188, 50, 'poda1.jpg'),
	(189, 50, 'poda2.jpg'),
	(190, 50, 'poda3.jpg'),
	(191, 50, 'poda4.jpg'),
	(192, 50, 'poda5.jpg'),
	(193, 51, 'cdc1.jpg'),
	(194, 51, 'cdc2.jpg'),
	(195, 51, 'cdc3.jpg'),
	(196, 51, 'cdc4.jpg'),
	(197, 51, 'cdc5.jpg'),
	(198, 52, 'tmahw1.jpg'),
	(199, 52, 'tmahw2.jpg'),
	(200, 52, 'tmahw3.jpg'),
	(201, 52, 'tmahw4.jpg'),
	(202, 53, 'pegsl1.jpg'),
	(203, 53, 'pegsl2.jpg'),
	(204, 53, 'pegsl3.jpg'),
	(205, 53, 'pegsl4.jpg'),
	(206, 53, 'pegsl5.jpg'),
	(207, 54, 'pu1.jpg'),
	(208, 54, 'pu2.jpg'),
	(209, 54, 'pu3.jpg'),
	(210, 54, 'pu4.jpg'),
	(211, 54, 'pu5.jpg'),
	(212, 55, 'mdsl1.jpg'),
	(213, 55, 'mdsl2.jpg'),
	(214, 55, 'mdsl3.jpg'),
	(215, 55, 'mdsl4.jpg'),
	(216, 55, 'mdsl5.jpg'),
	(217, 56, 'psp1.jpg'),
	(218, 56, 'psp2.jpg'),
	(219, 56, 'psp3.jpg'),
	(220, 56, 'psp4.jpg'),
	(221, 56, 'psp5.jpg'),
	(222, 8, 'zulai1.jpeg'),
	(223, 8, 'zulai2.jpeg'),
	(224, 8, 'zulai3.jpeg'),
	(225, 8, 'zulai4.jpeg'),
	(226, 8, 'zulai5.jpeg'),
	(232, 1, 'pqI1.jpg'),
	(233, 1, 'pqI3.jpg'),
	(234, 1, 'pqI4.jpg'),
	(235, 1, 'pqI5.jpeg'),
	(236, 1, 'pqI6.jpg'),
	(237, 2, 'pevl1.jpg'),
	(238, 2, 'pevl2.jpg'),
	(239, 2, 'pevl3.jpg'),
	(240, 2, 'pevl4.jpg'),
	(241, 2, 'pevl5.jpg'),
	(242, 3, 'gr1.jpg'),
	(243, 3, 'gr2.jpg'),
	(244, 3, 'gr3.jpg'),
	(247, 4, 'masp1.jpg'),
	(248, 4, 'masp2.jpeg'),
	(249, 4, 'masp3.jpg'),
	(250, 4, 'masp4.jpeg'),
	(251, 4, 'masp5.jpg'),
	(252, 5, 'cs1.jpg'),
	(253, 5, 'cs2.jpg'),
	(254, 5, 'cs3.jpg'),
	(255, 5, 'cs4.jpg'),
	(256, 5, 'cs5.jpg'),
	(257, 7, 'step1.jpg'),
	(258, 7, 'step2.jpg'),
	(259, 7, 'step3.jpg'),
	(260, 7, 'step4.jpg'),
	(261, 7, 'step5.jpg'),
	(262, 9, 'vvb1.jpg'),
	(263, 9, 'vvb2.jpg'),
	(264, 9, 'vvb3.jpg'),
	(265, 9, 'vvb4.jpg'),
	(266, 9, 'vvb5.jpg'),
	(267, 10, 'kas1.jpg'),
	(268, 10, 'kas2.jpg'),
	(269, 10, 'kas3.jpg'),
	(270, 10, 'kas4.jpg'),
	(271, 10, 'kas5.jpg'),
	(272, 11, 'bnsr1.jpg'),
	(273, 11, 'bnsr2.jpg'),
	(274, 11, 'bnsr3.jpg'),
	(275, 11, 'bnsr4.jpg'),
	(276, 11, 'bnsr5.jpg'),
	(277, 12, 'pcd1.jpg'),
	(278, 12, 'pcd2.jpg'),
	(279, 12, 'pcd3.jpg'),
	(280, 12, 'pcd4.jpg'),
	(281, 12, 'pcd5.jpg'),
	(282, 13, 'pcij1.jpg'),
	(283, 13, 'pcij2.jpg'),
	(284, 13, 'pcij3.jpg'),
	(285, 13, 'pcij4.jpg'),
	(286, 13, 'pcij5.jpg'),
	(287, 14, 'pzsp1.jpg'),
	(288, 14, 'pzsp2.jpg'),
	(289, 14, 'pzsp3.jpg'),
	(290, 14, 'pzsp4.jpg'),
	(291, 14, 'pzsp5.jpg'),
	(292, 15, 'pei1.jpg'),
	(293, 15, 'pei2.jpg'),
	(294, 15, 'pei3.jpg'),
	(295, 15, 'pei4.jpg'),
	(296, 15, 'pei5.jpg'),
	(298, 6, 'ilhatam3.jpg'),
	(299, 6, 'ilhatam2.jpg'),
	(300, 6, 'ilhatam1.jpg');

-- Copiando estrutura para tabela sampapoint.lugar
CREATE TABLE IF NOT EXISTS `lugar` (
  `codLocal` int NOT NULL AUTO_INCREMENT,
  `nomeLocal` varchar(50) COLLATE utf8mb3_bin NOT NULL,
  `horarioLocal` varchar(100) COLLATE utf8mb3_bin NOT NULL,
  `precoLocal` varchar(20) COLLATE utf8mb3_bin NOT NULL,
  `cepLugar` varchar(10) COLLATE utf8mb3_bin NOT NULL,
  `ruaLugar` varchar(100) COLLATE utf8mb3_bin NOT NULL,
  `bairroLugar` varchar(100) COLLATE utf8mb3_bin NOT NULL,
  `cidadeLugar` varchar(100) COLLATE utf8mb3_bin NOT NULL,
  `numeroLugar` varchar(100) COLLATE utf8mb3_bin DEFAULT NULL,
  `descLugar` varchar(1000) COLLATE utf8mb3_bin NOT NULL,
  `latLugar` float DEFAULT NULL,
  `lngLugar` float DEFAULT NULL,
  `fotoPerfilLugar` varchar(100) COLLATE utf8mb3_bin DEFAULT NULL,
  PRIMARY KEY (`codLocal`)
) ENGINE=InnoDB AUTO_INCREMENT=57 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_bin;

-- Copiando dados para a tabela sampapoint.lugar: ~56 rows (aproximadamente)
INSERT INTO `lugar` (`codLocal`, `nomeLocal`, `horarioLocal`, `precoLocal`, `cepLugar`, `ruaLugar`, `bairroLugar`, `cidadeLugar`, `numeroLugar`, `descLugar`, `latLugar`, `lngLugar`, `fotoPerfilLugar`) VALUES
	(1, 'Parque Ibirapuera', 'Todos os Dias das 05h00 às 00h00', 'Gratuito', '01311-000', 'Avenida Paulista', 'Bela Vista', 'São Paulo', '', 'Habitualmente conhecido como o parque mais visitado da américa latina, o Parque Ibirapuera possui em sua totalidade mais de 1.580.000 metros de extensão, dispondo desde patrimônios tombados como também uma bela área verde ao ar livre, um espaço com mais de 314 espécies de animais, além de eventos célebres e memoráveis todos os anos, tal qual que vira e mexe é sediado shows e atrações que atrai muitas pessoas, ainda mais que estes são em sua maioria gratuitos e abertos ao público. ', -23.5883, -46.6589, 'Parque Ibiapuera.jpg'),
	(2, 'Parque Villa-Lobos', 'Todos os Dias das 05H30 às 19H30', 'Gratuito', '05461-010', 'Avenida Professor Fonseca Rodrigues', 'Alto de Pinheiros', 'São Paulo', '', 'O Parque Villa-Lobos, cuja alcunha é feita em homenagem ao ilustríssimo compositor Heitor Villa-Lobos, trata-se de um lugar localizado em Alto dos Pinheiros, São Paulo, onde compreende vários bosques, jardins, quadras e instalações esportivas, consistindo em um consenso popular a principal prática em termos de lazer o passeio com bicicletas, skates, patins, patinetes e entre outros, tratando se de um ponto bem atrativo às famílias e grupos de amigos em feriados e em finais de semana. ', -23.5467, -46.7211, 'Parque Estadual Villa Lobos.jpg'),
	(3, 'Galeria do Rock', 'Segunda a Sexta das 09h00 às 19h00, \r\nSábado das 09h00 ás 18h00 e \r\nDomingo fechado', 'Gratuito', '01035-000', 'Avenida São João', 'Centro', 'São Paulo', '', 'A Galeria do Rock consiste em um centro comercial com mais de 450 lojas em de 7 andares mais uma arquitetura sem igual, a qual prevalece o comércio de artigos, itens e produtos relacionados ao gênero rock, hip-hop, skate e tribos urbanas no geral, além de conteúdos da cultura pop como livros e revistas, em síntese lá tem de tudo e mais um pouco quando se trata de gostos. ', -23.5439, -46.6389, 'Galeria do Rock.jpg'),
	(4, 'MASP', 'Terça a Domingo das 10h00 às 18h00 e as Segunda fechado', 'BRL25 e BRL50', '01310-200', 'Avenida Paulista', 'Bela Vista', 'São Paulo', '1578', 'Sendo sua fundação remontando em 1947 pelo empresário e mecenas Assis Chateaubriand (1892-1968), O Museu de Arte de São Paulo Assis Chateaubriand (conhecido também pelo acrônimo MASP) é um marco da história brasileira pois é o primeiro museu moderno no país, com um acevo de mais de 11 mil obras que remonta tanto a arte europeia, africana, asiática e por fim tupiniquim. Atualmente o MASP está dando uma maior atenção à exposição de histórias coletivas e individuais, tal qual histórias da sexualidade (2017), as histórias afro atlânticas (2018), as histórias feministas/histórias das mulheres (2019). ', -23.5611, -46.6558, 'MASP.jpg'),
	(5, 'Catedral da Sé', 'Todos os Dias das 08h00 às 18h00', 'Gratuito', '01001-000', 'Praça da Sé', 'Sé', 'São Paulo', '', ' Comumente referida como Catedral da Sé, a Catedral Metropolitana de São Paulo é o principal templo católico da cidade de São Paulo, sua história remonta desde o século 16, mas a catedral atual só foi vir a ser concebida neste famigerado estilo neogótico no século XX, graças ao árduo trabalho do arquiteto alemão Maximilian Emil Hehl. Hoje a catedral recebe vários visitantes todos os dias, e entre eles fiéis, sendo assim a sua estrutura chama a atenção por todos que ali passam. ', -23.5511, -46.6342, 'Catedral da Se.jpg'),
	(6, 'Parque Ecológico Ilha do Tamboré', 'Todos os dias das 07h00 às 17h00', 'Gratuito', '06465-140', 'Avenida Doutor Dib Sauaia Neto', 'Alphaville Empresarial', 'Barueri', '', 'O Parque Ecológico Ilha do Tamboré ou Parque Ecológico do Tietê foi inaugurado em 1982, e desde então vem sendo arborizado e cuidado pelo governo desde então, sendo revitalizado em 2004, com um grande acervo em termos de fauna e flora, este parque vira uma boa opção a pessoas naturalistas e amantes da natureza, com várias áreas de lazer e os passeios de trenzinho, pedalinho e triciclo em família ou só.', -23.5038, -46.8596, 'Parque Ecologica de Barueri.jpg'),
	(7, 'Sitiolândia Eco Park', 'Sábado e Domingo das 09H00 às 17h00; Segunda a Sexta fechado', 'BRL60', '07700-000', 'Estrada professor Eduardo Soares', 'Parque Santa Inês', 'Caieiras', '', 'A Sitiolândia Eco Park, em uma área de 74.000 m2 na Serra da Cantareira, é um parque a qual se baseia principalmente em mais de 35 atrações pedagógicas e recreativas para a família e a escola, que vai desde tirolesa, teatro, o mundo dinossauro, parque de diversões, arvorismo, cultura indígena, labirinto e entre outros, estando em atividade há 24 anos. ', -23.4779, -46.633, 'Sitiolandia Eco Park.jpg'),
	(8, 'Templo Zu-Lai', 'Sexta da 12h00 às 17h00;Sábado e Domingo das 09h30 às 17h00; Segunda a Quinta fechado', 'Gratuito', '06705-490', 'Estrada Fernando Nobre', 'Parque Rincão', 'Cotia', '1461', 'O Templo Zu-Lai é o maior templo budista da américa latina sob o monastério Fo Guang Shan, este atualmente conhecido foi fundado em 2003 e sua localização é no município de Cotia, consistindo em um lugar do culto e prática ao budismo a qual aceita visitas, mas há um procedimento e regras a serem seguidos como consta no próprio site: https://templozulai.org.br', -23.5869, -46.8831, 'Templo Zu Lai.jpg'),
	(9, 'Vila Viking Brasil', 'Apenas por Agendamento', 'Orçamento', '06950-000', 'Estrada Particular', 'Sítio Gervásio', 'Juquitiba', '', 'A Vila Viking Brasil é um museu vivo ou um espaço cultural que recria o período viking (sec. VIII ao XI), com várias atividades que revivem o que seria a vida de um viking médio na época com vários eventos e atrações, como por exemplo o tiro com arco e flecha, música com elementos tradicionais nórdicos, apresentação de combate, consumo de hidromel, apresentação de utensílios e estruturas vikings junto aos profissionais explicando como era o cotidiano mais o conhecimento da cultura. ', -23.9049, -47.1139, 'Vila Viking Brasil.jpg'),
	(10, 'Kartódromo Aldeia da Serra', 'Apenas com Agendamento', 'Orçamento', '06423-150', 'Estrada Doutor Yojiro Takaoka', 'Aldeia da Serra', 'Barueri', '210', 'O Kartódromo Aldeia da Serra é um a pista outdoor (ao ar livre) de 50.000.00 m² a qual ocorre corridas ou treinos de karts, com uma infraestrutura profissional que é sinônimo de segurança e bem-estar, possuindo um placar eletrônico, uma arquibancada e um restaurante aos visitantes. ', -23.509, -46.9314, 'Kartodromo Aldeia da Serra.jpg'),
	(11, 'Basílica de Nossa Senhora do Rosáio', 'Sábado das 16h00 às 17h30; Domingo das 09h15 às 16h30; Segunda a Sexta fechado', 'Gratuito', '07733-005', 'Rua Avaé', 'Parque Santa Inês', 'Caieiras', '430', 'A Basílica, construída em arquitetura neogótica e com 60 metros de altura, tem paredes, vitrais e teto ricamente decorados com figuras religiosas e desenhos nas cores azul, vermelho e dourado e que teve como inspiração os grandes templos europeus como as basílicas medievais Notre Dame e Capela Cistina, foi construida nas proximidades de Caeiras pelos patronos da Igreja Católica Apostólica Romana no ano de 2006 e se tornou símbolo de solenidade e sacro para o centro da região. ', -23.4089, -46.6706, 'Basilica de Nossa Senhora do Rosario.jpg'),
	(12, 'Parque Celso Daniel', 'Todos os dias das 06h00 às 22h00', 'Gratuito', '09080-000', 'Avenida Dom Pedro II', 'Jardim', 'Santo André', '940', ' O Parque Celso Daniel é um dos principais pontos turísticos e opções de lazer ao ar livre do município de Santo André, dado aos seus 64 mil m2 mais as suas infraestruturas dispondo de lanchonetes, vestiários e corrimões adaptados para pessoas com deficiência, áreas arborizadas, revistaria, quadras para as práticas do esporte e playgrounds para crianças. ', -23.6469, -46.5372, 'Parque Celso Daniel.jpg'),
	(13, 'Parque Centenário da Imigração Japonesa', 'Todos os dias das 07H00 às 17h00', 'Gratuito', '08773-380', 'Avenida Francisco Rodrigues Filho', 'Vila Mogilar', 'Mogi das Cruzes', '', 'Inaugurado em junho de 2008, o Parque Centenário da Imigração Japonesa de Mogi das Cruzes conta com mais de 215 mil metros de área, possuindo 4 lagos com pontes flutuantes, um museu histórico, objetos e utensílios doados pelos imigrantes junto a toda uma ambientação e arquitetura nipônica, e além de é claro quadras esportivas e áreas de lazer. ', -23.5088, -46.1718, 'Parque Centenario da Imigracao Japonesa.jpg'),
	(14, 'Parque Zoológico de São Paulo', 'Todos os dias das 09h00 às 16h00', 'BRL25', '04301-905', 'Avenida Miguel Estefno', 'Ãgua Funda', 'São Paulo', '4241', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type a', -23.6512, -46.6207, 'Parque Zoologico de Sao Paulo.jpg'),
	(15, 'Parque Estadual Itaberaba', 'Todos os dias das 08H00 às 17h00', 'Gratuito', '02377-000', 'Rua do Horto', 'Horto Florestal', 'São Paulo', '262', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type a', -23.1992, -46.4028, 'Parque Estadual Itaberaba.jpg'),
	(16, 'Museu Municipal de Barueri', 'Sábado, Domingo e Feriados das 09h00 às 14h00', 'Gratuito', '06420-130', 'Avenida Henrique Gonçalves Baptista', 'Jardim Belval', 'Barueri', '359', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type a', -23.5122, -46.8944, 'Museu Municipal de Barueri.jpg'),
	(17, 'Vale Encantado Thermas Park', 'Todos os dias das 09h00 às 17h00', 'BRL90', '08940-000', 'Estrada do Sertãozinho', 'Cruz das Almas', 'Biritiba-Mirim', '', 'Vale Encantado Thermas Park é um parque aquático sitiado no município de Biritiba-Mirim com várias atrações e práticas aos visitantes, desde a pesca, passeio a cavalo, churrasqueiras, áreas de lazer e várias piscinas temáticas e toboáguas para a família.  ', -23.6167, -46.0432, 'Vale Encantado Thermas Park.jpg'),
	(18, 'Paróquia São Benedito', 'Sábado e Domingos das 09h00 às 16h00; Segunda a sexta fechado', 'Gratuito', '08940-000', 'Rua Gildo Sevali', 'Centro Histórico de São Paulo', 'Biritiba-Mirim', '243', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type a', -23.5733, -46.0389, 'Paroquia Sao Benedito.jpg'),
	(19, 'Parque Estadual Cantareira', 'Quarta a Domingo das 08h00 às 16h00; Segunda e Terça fechado', 'Gratuito', '02377-000', 'Rua do Horto', 'Horto Florestal', 'São Paulo', '1799', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type a', -23.4554, -46.6366, 'Parque Estadual Cantareira Nucleo Pedra Grande.jpg'),
	(20, 'Anhanguera Parque Shopping', 'Todos os dias das 10h00 às 22h00', 'Gratuito', '07791-842', 'Rua Jean Anastace Kovelis', 'Ipês (Polvilho)', 'Cajamar', '123', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type a', -23.4082, -46.8569, 'Anhanguera Parque Shopping.jpg'),
	(21, 'Museu Municipal Casa da Memória', 'Fechado Temporariamente', 'Gratuito', '07752-060', 'Praça Josão Rodrigues do Nascimento', 'Água Fria', 'Cajamar', '30', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type a', -23.3645, -46.8725, 'Museu Municipal Casa da Memoria.jpg'),
	(22, 'Parque Estadual Gabriel Chucre', 'Todos os dias das 06h00 às 18h00', 'Gratuito', '06310-260', 'Rua Consolação', 'Vila Gustavo Correia', 'Carapicuíba', '505', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type a', -23.5159, -46.8332, 'Parque Estadual Gabriel Chucre.jpg'),
	(23, 'Parque do Planalto', 'Todos os dias das 06h00 às 18h00', 'Gratuito', '06362-160', 'Rua Serra de Mailaski', 'Jardim Planalto', 'Carapicuíba', '', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type a', -23.5558, -46.8406, 'Parque do Planalto.jpg'),
	(24, 'Thermas da Mata', 'Quarta a Domingo das 10h00 às 17h00; Segunda e Terça fechado', 'BRL90', '06719-500', 'Estrada Morro Grande', 'Jardim Ásis', 'Cotia', '3000', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type a', -23.6238, -46.9522, 'Thermas da Mata.jfif'),
	(25, 'Parque do Paço', 'Todos os dias das 06h00 às 21h00', 'Gratuito', '09911-160', 'Avenida Antônio Piranga', 'Centro', 'Diadema', '1380', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type a', -23.6862, -46.6097, 'Parque do Paco.jpg'),
	(26, 'Borboletário de Diadema', 'Quarta a Sexta das 09h00 às 15h30; Segunda, Terça, Sábado e Domingo fechado', 'Gratuito', '09970-000', 'R. Ipita', 'Inamar', 'Diadema', '193', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type a', -23.7193, -46.6102, 'Borboletario de Diadema.jpg'),
	(27, 'Praça das Artes', 'Todos os dias das 07h00 às 20h00', 'Gratuito', '06803-420', 'Rua da Matriz', 'Centro', 'Embu das Artes', '16A', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type a', -23.6498, -46.8527, 'Praca das Artes Embu das Artes.jpg'),
	(28, 'Estadio Municipal Hermínio Espósito', 'Não Informado', 'Gratuito', '06803-460', 'Alameda Fernando Batista Medina', 'Centro', 'Embu das Artes', '120', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type a', -23.6534, -46.8568, 'Estadio Municipal Herminio Esposito.jpg'),
	(29, 'Estação Ferroviária de Embu-Guaçu', 'Todos os dias das 06h00 às 22h00', 'BRL15', '06900-000', 'R. Jorge Gibel', 'Vila Louro', 'Embu-Guaçu', '119', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type a', -23.8276, -46.8133, 'Estacao Ferroviaria de EmbuGuacu.jpg'),
	(30, 'Praça Henrique Schunk', 'Todos os dias', 'Gratuito', '06900-000', 'Praça Henrique Schunk', 'Cipé', 'Embu-Guaçu', '', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type a', -23.8777, -46.7933, 'Praca Henrique Schunk.jpg'),
	(31, 'Secretaria De Arte e Cultura', 'Todos os dias das 08h00 às 17h00', 'Gratuito', '08503-110', 'Travessa do Castelo', 'Jardim do Castelo', 'Ferraz de Vasconcelos', '9', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type a', -23.5478, -46.36, 'Secretaria De Arte e Cultura.jpg'),
	(32, 'Parque Municipal Nosso Recanto', 'Todos os dias das 06h00 às 16h00', 'Gratuito', '08502-080', 'Rua João Ramalho', 'Jardim Ferrazense', 'Ferraz de Vasconcelos', '123', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type a', -23.5336, -46.3583, 'Parque Municipal Nosso Recanto.jpg'),
	(33, 'Paróquia Menino Jesus e São Benedito', 'Segunda a Sábado das 08h00 às 15h00; Domingo fechado', 'Gratuito', '07990-030', 'Rua Antônio Soriano Dias', 'Belém Capela', 'Francisco Morato', '1', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type a', -23.2761, -46.7422, 'Paroquia Menino Jesus e Sao Benedito.jpg'),
	(34, 'Parque da Criança', 'Todos os dias das 06h00 às 20h00', 'BRL80', '07950-095', 'Rua São Domingos', 'Jardim Vassouras', 'Francisco Morato', '200', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type a', -23.2799, -46.7286, 'Parque da Crianca.jpg'),
	(35, 'Parque Estadual do Juquery', 'Terça a Domingo das 08h00 às 17h00; Segunda fechado', 'Gratuito', '07859-390', 'Rua Miguel Segundo Lerussi', 'Parque Industrial', 'Franco da Rocha', '', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type a', -23.3534, -46.6948, 'Parque Estadual do Juquery.jpg'),
	(36, 'Cachoeira Quarta Colonia', 'Todos os dias', 'Gratuito', '07864-260', 'Rua Pardal', 'Parque Pretoria', 'Franco da Rocha', '', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type a', -23.3251, -46.6906, 'Cachoeira Quarta Colonia.jpg'),
	(37, 'Guararema Acqua Thermas', 'Temporada', 'BRL100', '08900-000', 'Estrada Josão Marcelinne', 'Goiabal', 'Guararema', '760', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type a', -23.3568, -46.0601, 'Guararema Acqua Thermas.jpg'),
	(38, 'Trem de Guararema', 'Sábado e Domingo das 14h00 às 16h00; Segunda a Sexta fechado', 'BRL20', '08900-000', 'R. Dr. Falcão', 'Centro', 'Guararema', '4', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type a', -23.4139, -46.0315, 'Trem de Guararema.jpg'),
	(39, 'Internacional Shopping', 'Todos os dias das 10h00 às 22h00', 'Gratuito', '07034-010', 'Rodovia Presidente Dutra', 'Vázea do Palácio', 'Guarulhos', '295', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type a', -23.4877, -46.5466, 'Internacional Shopping.jpg'),
	(40, 'Parque Bosque Maia', 'Todos os dias das 06h00 às 21h30', 'Gratuito', '07115-260', 'Rua Domingos Antonelli', 'Jardim Maria Helena', 'Guarulhos', '', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type a', -23.4566, -46.5304, 'Parque Bosque Maia.jpg'),
	(41, 'Lago dos Patos', 'Todos os dias das 09h00 às 20h00', 'Gratuito', '07074-030', 'Rua Nossa Senhora de Lourdes', 'Vila Galvão', 'Guarulhos', '723', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type a', -23.4522, -46.5623, 'Lago dos Patos.jpg'),
	(42, 'Templo Kinkaku-Ji', 'Todos os dias das 09h00 às 16h00', 'Gratuito', '06872-390', 'Rua Camarão', 'Chácara das Palmeiras', 'Itapecerica da Serra', '220', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type a', -23.746, -46.8655, 'Templo Kinkaku-Ji.jpg'),
	(43, 'Clube dos Pimentas', 'Todos os dias das 09h00 às 17h00', 'BRL90', '06854-000', 'Avenida Guacy Fernandes Domingues', 'Embu Mirim', 'Itapecerica da Serra', '325', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type a', -23.7, -46.8483, 'Clube dos Pimentas.jpg'),
	(44, 'Pesqueiro Boa Vida', 'Todos os dias das 07h00 às 17h30', 'BRL30', '06685-300', 'Rua dos Desbravadores', 'Chácaras Monte Serrat', 'Itapevi', '', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type a', -23.5407, -46.9965, 'Pesqueiro Boa Vida.jpg'),
	(45, 'Magic Games Itaquí Garden Shopping', 'Todos os dias das 10h00 às 22h00', 'BRL50', '08598-000', 'Estrada Municipal do Mandi', 'Mandi', 'Itaquaquecetuba', '1205', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type a', -23.4757, -46.3264, 'Magic Games Itaqua Garden Shopping.jfif'),
	(46, 'Parque Ecológico Mario do Canto', 'Todos os dias das 05h00 às 19h00', 'Gratuito', '08571-020', 'Rua Cabrilia Paulista', 'Estação', 'Itaquaquecetuba', '', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type a', -23.48, -46.3502, 'Parque Ecologico Mario do Canto.jpg'),
	(47, 'Praça de Eventos de Jandira', 'Todos os dias', 'Gratuito', '06600-035', 'Rua Rúbens Lopes da Silva', 'Centro', 'Jandira', '106', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type a', -23.5306, -46.8994, 'Praca de Eventos de Jandira.jpg'),
	(48, 'Jandira Plaza Shopping', 'Todos os dias das 8h30 às 22h00', 'Gratuito', '06600-045', 'Rua Ricarte Sewaybricker', 'Centro', 'Jandira', '52', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type a', -23.528, -46.9028, 'Jandira Plaza Shopping.jpg'),
	(49, 'Viva Ecoparque', 'Sábado e Domingo das 09h00 às 17h00; Segunda a Sexta fechado', 'BRL40', '06900-000', 'Estrada do Jacuba', 'Jardim das Palmeiras', 'Juquitiba', '2011', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type a', -23.9455, -46.9972, 'Viva Ecoparque.jpg'),
	(50, 'Pico do Olho D\'agua', 'Todos os dias ', 'Gratuito', '07600-000', 'Av. Georgetown', '300', 'Mairiporã', '669', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type a', -23.2978, -46.581, 'Pico do Olho.jpg'),
	(51, 'Cachoeira da Caceia', 'Todos os dias', 'Gratuito', '07600-000', 'Estr. Armando Barbosa de Almeida', 'Não indicado', 'Mairiporã', '6300', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type a', -23.3191, -46.632, 'Cachoeira da Caceia.jpg'),
	(52, 'Teatro Municipal Anselmo Haraldt Walendy', 'Apenas por Agenda', 'Orçamento', '09370-575', 'Rua Gabriel Marques', 'Vila Noâmia', 'Mauá', '353', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type a', -23.6661, -46.4666, 'Teatro Municipal Anselmo Haraldt Walendy.jpg'),
	(53, 'Parque Ecológico da Gruta Santa Luzia', 'Todos os dias das 07h00 às 16h45', 'Gratuito', '09330-151', 'Rua Luzia da Silva Itabaiana', 'Jardim Itapeva', 'Mauá', '101', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type a', -23.677, -46.4088, 'ParqueEcologico da Gruta Santa Luzia.jpg'),
	(54, 'Pico do Urubu', 'Todos os dias', 'Gratuito', '08710-025', 'Rua Coronel Souza Franco', 'Centro', 'Mogi das Cruzes', '', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type a', -23.4841, -46.2067, 'Pico do Urubu.jpg'),
	(55, 'Museu Dimitri Sensaud de Lavaud', 'Segunda a Sábado das 10h00 às 16h30; Domingo fechado', 'Gratuito', '06090-027', 'Avenida dos Autonomistas', 'Centro', 'Osasco', '4001', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type a', -23.5295, -46.788, 'Museu Dimitri Sensaud de Lavaud.jpg'),
	(56, 'Pinacoteca do Estado São Paulo', 'Todos os dias das 10h00 às 18h00', 'Gratuito', '01120-010', 'Praça da Luz', 'Bom Retiro', 'São Paulo', '2', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type a', -23.5342, -46.6336, 'Pinacoteca de Sao Paulo.jpg');

-- Copiando estrutura para tabela sampapoint.perfil
CREATE TABLE IF NOT EXISTS `perfil` (
  `codUsuario` int NOT NULL AUTO_INCREMENT,
  `status` int NOT NULL,
  `nome` varchar(50) COLLATE utf8mb3_bin NOT NULL,
  `email` varchar(50) COLLATE utf8mb3_bin NOT NULL,
  `usuario` varchar(15) COLLATE utf8mb3_bin NOT NULL,
  `senha` varchar(10) COLLATE utf8mb3_bin NOT NULL,
  `cepUsuario` varchar(10) COLLATE utf8mb3_bin NOT NULL,
  `ruaUsuario` varchar(100) COLLATE utf8mb3_bin NOT NULL,
  `bairroUsuario` varchar(100) COLLATE utf8mb3_bin NOT NULL,
  `cidadeUsuario` varchar(100) COLLATE utf8mb3_bin NOT NULL,
  `estadoUsuario` varchar(100) COLLATE utf8mb3_bin NOT NULL,
  `numCasaUsuario` int DEFAULT NULL,
  `biografia` varchar(200) COLLATE utf8mb3_bin DEFAULT NULL,
  `nomeFotoPerfil` varchar(200) COLLATE utf8mb3_bin DEFAULT NULL,
  PRIMARY KEY (`codUsuario`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_bin;

-- Copiando dados para a tabela sampapoint.perfil: ~2 rows (aproximadamente)
INSERT INTO `perfil` (`codUsuario`, `status`, `nome`, `email`, `usuario`, `senha`, `cepUsuario`, `ruaUsuario`, `bairroUsuario`, `cidadeUsuario`, `estadoUsuario`, `numCasaUsuario`, `biografia`, `nomeFotoPerfil`) VALUES
	(1, 1, 'ADMINISTRADOR', '', 'sampapoint262', 'sppoint262', '', '', '', '', '', NULL, NULL, NULL),
	(4, 0, 'Mônick Proença', 'monick@gmail.com', 'proencamoni', 'monick123', '06535-204', 'Rua da Tartaruga', 'Cidade São Pedro - Gleba B', 'Santana de Parnaíba', 'SP', 177, 'Olá! Eu sou Mônick e gosto muito de gatos e de fazer obras artísticas. Meu passatempo favorito é sair com meus amigos.', 'img_perfil.jpeg');

-- Copiando estrutura para tabela sampapoint.suporte
CREATE TABLE IF NOT EXISTS `suporte` (
  `codSuporte` int NOT NULL AUTO_INCREMENT,
  `codUsuario` int NOT NULL,
  `email` varchar(100) COLLATE utf8mb3_bin DEFAULT NULL,
  `statusEmail` varchar(20) COLLATE utf8mb3_bin NOT NULL,
  PRIMARY KEY (`codSuporte`),
  KEY `fk_perfil_suporte` (`codUsuario`),
  CONSTRAINT `fk_perfil_suporte` FOREIGN KEY (`codUsuario`) REFERENCES `perfil` (`codUsuario`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_bin;

-- Copiando dados para a tabela sampapoint.suporte: ~0 rows (aproximadamente)

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
